/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/umkc/umkc_robot_2014_arduino/wesley/ros/src/wesley/msg/arm_point.msg
 *
 */


#ifndef WESLEY_MESSAGE_ARM_POINT_H
#define WESLEY_MESSAGE_ARM_POINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wesley
{
template <class ContainerAllocator>
struct arm_point_
{
  typedef arm_point_<ContainerAllocator> Type;

  arm_point_()
    : direct_mode(false)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , p(0.0)
    , r(0.0)
    , cmd()  {
    }
  arm_point_(const ContainerAllocator& _alloc)
    : direct_mode(false)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , p(0.0)
    , r(0.0)
    , cmd(_alloc)  {
    }



   typedef uint8_t _direct_mode_type;
  _direct_mode_type direct_mode;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _p_type;
  _p_type p;

   typedef float _r_type;
  _r_type r;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _cmd_type;
  _cmd_type cmd;




  typedef boost::shared_ptr< ::wesley::arm_point_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wesley::arm_point_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct arm_point_

typedef ::wesley::arm_point_<std::allocator<void> > arm_point;

typedef boost::shared_ptr< ::wesley::arm_point > arm_pointPtr;
typedef boost::shared_ptr< ::wesley::arm_point const> arm_pointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wesley::arm_point_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wesley::arm_point_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wesley

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'wesley': ['/home/umkc/umkc_robot_2014_arduino/wesley/ros/src/wesley/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wesley::arm_point_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wesley::arm_point_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wesley::arm_point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wesley::arm_point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wesley::arm_point_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wesley::arm_point_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wesley::arm_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a7c5188638382dfddf2aa151cdefcc50";
  }

  static const char* value(const ::wesley::arm_point_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa7c5188638382dfdULL;
  static const uint64_t static_value2 = 0xdf2aa151cdefcc50ULL;
};

template<class ContainerAllocator>
struct DataType< ::wesley::arm_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wesley/arm_point";
  }

  static const char* value(const ::wesley::arm_point_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wesley::arm_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# wesley::arm_point\n\
\n\
bool direct_mode\n\
float32 x\n\
float32 y\n\
float32 z\n\
float32 p\n\
float32 r\n\
string cmd\n\
\n\
";
  }

  static const char* value(const ::wesley::arm_point_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wesley::arm_point_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direct_mode);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.p);
      stream.next(m.r);
      stream.next(m.cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct arm_point_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wesley::arm_point_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wesley::arm_point_<ContainerAllocator>& v)
  {
    s << indent << "direct_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.direct_mode);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "p: ";
    Printer<float>::stream(s, indent + "  ", v.p);
    s << indent << "r: ";
    Printer<float>::stream(s, indent + "  ", v.r);
    s << indent << "cmd: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WESLEY_MESSAGE_ARM_POINT_H
