/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/umkc/wesley/umkc_robot_2014_arduino/wesley/ros/src/imu_tools/imu_filter_madgwick/srv/imu_yaw.srv
 *
 */


#ifndef IMU_FILTER_MADGWICK_MESSAGE_IMU_YAW_H
#define IMU_FILTER_MADGWICK_MESSAGE_IMU_YAW_H

#include <ros/service_traits.h>


#include <imu_filter_madgwick/imu_yawRequest.h>
#include <imu_filter_madgwick/imu_yawResponse.h>


namespace imu_filter_madgwick
{

struct imu_yaw
{

typedef imu_yawRequest Request;
typedef imu_yawResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct imu_yaw
} // namespace imu_filter_madgwick


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::imu_filter_madgwick::imu_yaw > {
  static const char* value()
  {
    return "08cb8274b6ddb17af5a842bca0b17db1";
  }

  static const char* value(const ::imu_filter_madgwick::imu_yaw&) { return value(); }
};

template<>
struct DataType< ::imu_filter_madgwick::imu_yaw > {
  static const char* value()
  {
    return "imu_filter_madgwick/imu_yaw";
  }

  static const char* value(const ::imu_filter_madgwick::imu_yaw&) { return value(); }
};


// service_traits::MD5Sum< ::imu_filter_madgwick::imu_yawRequest> should match 
// service_traits::MD5Sum< ::imu_filter_madgwick::imu_yaw > 
template<>
struct MD5Sum< ::imu_filter_madgwick::imu_yawRequest>
{
  static const char* value()
  {
    return MD5Sum< ::imu_filter_madgwick::imu_yaw >::value();
  }
  static const char* value(const ::imu_filter_madgwick::imu_yawRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::imu_filter_madgwick::imu_yawRequest> should match 
// service_traits::DataType< ::imu_filter_madgwick::imu_yaw > 
template<>
struct DataType< ::imu_filter_madgwick::imu_yawRequest>
{
  static const char* value()
  {
    return DataType< ::imu_filter_madgwick::imu_yaw >::value();
  }
  static const char* value(const ::imu_filter_madgwick::imu_yawRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::imu_filter_madgwick::imu_yawResponse> should match 
// service_traits::MD5Sum< ::imu_filter_madgwick::imu_yaw > 
template<>
struct MD5Sum< ::imu_filter_madgwick::imu_yawResponse>
{
  static const char* value()
  {
    return MD5Sum< ::imu_filter_madgwick::imu_yaw >::value();
  }
  static const char* value(const ::imu_filter_madgwick::imu_yawResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::imu_filter_madgwick::imu_yawResponse> should match 
// service_traits::DataType< ::imu_filter_madgwick::imu_yaw > 
template<>
struct DataType< ::imu_filter_madgwick::imu_yawResponse>
{
  static const char* value()
  {
    return DataType< ::imu_filter_madgwick::imu_yaw >::value();
  }
  static const char* value(const ::imu_filter_madgwick::imu_yawResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IMU_FILTER_MADGWICK_MESSAGE_IMU_YAW_H
