"""autogenerated by genpy from wesley/arm_angle.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class arm_angle(genpy.Message):
  _md5sum = "ef33d4984a305fd75dffb44db14b17ea"
  _type = "wesley/arm_angle"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# wesley::arm_angle

uint16 base
uint16 shoulder
uint16 elbow
uint16 wrist_pitch
uint16 wrist_roll
uint16 hand

"""
  __slots__ = ['base','shoulder','elbow','wrist_pitch','wrist_roll','hand']
  _slot_types = ['uint16','uint16','uint16','uint16','uint16','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       base,shoulder,elbow,wrist_pitch,wrist_roll,hand

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(arm_angle, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.base is None:
        self.base = 0
      if self.shoulder is None:
        self.shoulder = 0
      if self.elbow is None:
        self.elbow = 0
      if self.wrist_pitch is None:
        self.wrist_pitch = 0
      if self.wrist_roll is None:
        self.wrist_roll = 0
      if self.hand is None:
        self.hand = 0
    else:
      self.base = 0
      self.shoulder = 0
      self.elbow = 0
      self.wrist_pitch = 0
      self.wrist_roll = 0
      self.hand = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_6H.pack(_x.base, _x.shoulder, _x.elbow, _x.wrist_pitch, _x.wrist_roll, _x.hand))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.base, _x.shoulder, _x.elbow, _x.wrist_pitch, _x.wrist_roll, _x.hand,) = _struct_6H.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_6H.pack(_x.base, _x.shoulder, _x.elbow, _x.wrist_pitch, _x.wrist_roll, _x.hand))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.base, _x.shoulder, _x.elbow, _x.wrist_pitch, _x.wrist_roll, _x.hand,) = _struct_6H.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_6H = struct.Struct("<6H")
