/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/umkc/umkc_robot_2014_arduino/wesley/ros/src/mega_caretaker/msg/MegaPacket.msg
 *
 */


#ifndef MEGA_CARETAKER_MESSAGE_MEGAPACKET_H
#define MEGA_CARETAKER_MESSAGE_MEGAPACKET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mega_caretaker/MotorCommand.h>

namespace mega_caretaker
{
template <class ContainerAllocator>
struct MegaPacket_
{
  typedef MegaPacket_<ContainerAllocator> Type;

  MegaPacket_()
    : msgType(0)
    , mCom()
    , payload(0)  {
    }
  MegaPacket_(const ContainerAllocator& _alloc)
    : msgType(0)
    , mCom(_alloc)
    , payload(0)  {
    }



   typedef int8_t _msgType_type;
  _msgType_type msgType;

   typedef  ::mega_caretaker::MotorCommand_<ContainerAllocator>  _mCom_type;
  _mCom_type mCom;

   typedef uint16_t _payload_type;
  _payload_type payload;




  typedef boost::shared_ptr< ::mega_caretaker::MegaPacket_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mega_caretaker::MegaPacket_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct MegaPacket_

typedef ::mega_caretaker::MegaPacket_<std::allocator<void> > MegaPacket;

typedef boost::shared_ptr< ::mega_caretaker::MegaPacket > MegaPacketPtr;
typedef boost::shared_ptr< ::mega_caretaker::MegaPacket const> MegaPacketConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mega_caretaker::MegaPacket_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mega_caretaker::MegaPacket_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mega_caretaker

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'mega_caretaker': ['/home/umkc/umkc_robot_2014_arduino/wesley/ros/src/mega_caretaker/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mega_caretaker::MegaPacket_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mega_caretaker::MegaPacket_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mega_caretaker::MegaPacket_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mega_caretaker::MegaPacket_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mega_caretaker::MegaPacket_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mega_caretaker::MegaPacket_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mega_caretaker::MegaPacket_<ContainerAllocator> >
{
  static const char* value()
  {
    return "70e1bad56237befa0ecfa4de7f08c859";
  }

  static const char* value(const ::mega_caretaker::MegaPacket_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x70e1bad56237befaULL;
  static const uint64_t static_value2 = 0x0ecfa4de7f08c859ULL;
};

template<class ContainerAllocator>
struct DataType< ::mega_caretaker::MegaPacket_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mega_caretaker/MegaPacket";
  }

  static const char* value(const ::mega_caretaker::MegaPacket_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mega_caretaker::MegaPacket_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 msgType\n\
MotorCommand mCom\n\
uint16 payload\n\
\n\
================================================================================\n\
MSG: mega_caretaker/MotorCommand\n\
int8 left\n\
int8 right\n\
\n\
";
  }

  static const char* value(const ::mega_caretaker::MegaPacket_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mega_caretaker::MegaPacket_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.msgType);
      stream.next(m.mCom);
      stream.next(m.payload);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MegaPacket_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mega_caretaker::MegaPacket_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mega_caretaker::MegaPacket_<ContainerAllocator>& v)
  {
    s << indent << "msgType: ";
    Printer<int8_t>::stream(s, indent + "  ", v.msgType);
    s << indent << "mCom: ";
    s << std::endl;
    Printer< ::mega_caretaker::MotorCommand_<ContainerAllocator> >::stream(s, indent + "  ", v.mCom);
    s << indent << "payload: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.payload);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MEGA_CARETAKER_MESSAGE_MEGAPACKET_H
