/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/umkc/wesley/umkc_robot_2014_arduino/wesley/ros/src/imu_tools/imu_filter_madgwick/srv/imu_yaw.srv
 *
 */


#ifndef IMU_FILTER_MADGWICK_MESSAGE_IMU_YAWRESPONSE_H
#define IMU_FILTER_MADGWICK_MESSAGE_IMU_YAWRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace imu_filter_madgwick
{
template <class ContainerAllocator>
struct imu_yawResponse_
{
  typedef imu_yawResponse_<ContainerAllocator> Type;

  imu_yawResponse_()
    : yaw(0.0)  {
    }
  imu_yawResponse_(const ContainerAllocator& _alloc)
    : yaw(0.0)  {
    }



   typedef double _yaw_type;
  _yaw_type yaw;




  typedef boost::shared_ptr< ::imu_filter_madgwick::imu_yawResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu_filter_madgwick::imu_yawResponse_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct imu_yawResponse_

typedef ::imu_filter_madgwick::imu_yawResponse_<std::allocator<void> > imu_yawResponse;

typedef boost::shared_ptr< ::imu_filter_madgwick::imu_yawResponse > imu_yawResponsePtr;
typedef boost::shared_ptr< ::imu_filter_madgwick::imu_yawResponse const> imu_yawResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imu_filter_madgwick::imu_yawResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imu_filter_madgwick::imu_yawResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace imu_filter_madgwick

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::imu_filter_madgwick::imu_yawResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_filter_madgwick::imu_yawResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_filter_madgwick::imu_yawResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_filter_madgwick::imu_yawResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_filter_madgwick::imu_yawResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_filter_madgwick::imu_yawResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imu_filter_madgwick::imu_yawResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "08cb8274b6ddb17af5a842bca0b17db1";
  }

  static const char* value(const ::imu_filter_madgwick::imu_yawResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x08cb8274b6ddb17aULL;
  static const uint64_t static_value2 = 0xf5a842bca0b17db1ULL;
};

template<class ContainerAllocator>
struct DataType< ::imu_filter_madgwick::imu_yawResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imu_filter_madgwick/imu_yawResponse";
  }

  static const char* value(const ::imu_filter_madgwick::imu_yawResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imu_filter_madgwick::imu_yawResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 yaw\n\
\n\
";
  }

  static const char* value(const ::imu_filter_madgwick::imu_yawResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imu_filter_madgwick::imu_yawResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct imu_yawResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu_filter_madgwick::imu_yawResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imu_filter_madgwick::imu_yawResponse_<ContainerAllocator>& v)
  {
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMU_FILTER_MADGWICK_MESSAGE_IMU_YAWRESPONSE_H
